# fly.toml app configuration file generated for resume-server on 2023-08-01T18:54:28-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "resume-server"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "den"
processes = []

[build]

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
